spring:
  application:
      name: cake-data-api-gateway
  cloud:
     gateway:
      discovery:
         locator:
            enabled: true
      routes:
         - id: cake-data-service
            uri:'http://localhost:8088'
           predicates:
              - Path=/cakes/**

server:
   port: 9090

